vim.wo.number = true -- line numbers
vim.o.relativenumber = true -- relative line numbers
-- vim.o.clipboard = 'unnamedplus' -- use system clipboard
-- vim.o.wrap = false
-- vim.o.sidescrolloff = 8
vim.o.scrolloff = 4 -- minimal number of screen lines to keep above and below the cursor
vim.o.linebreak = true
vim.o.ignorecase = true -- case insensitve searching
vim.o.smartcase = true -- makes search case sensitive if captials are used
vim.o.numberwidth = 2 -- set number column width to 2 {default 4}
vim.o.shiftwidth = 4 -- the number of spaces inserted for each indentation
vim.o.tabstop = 4 -- insert n spaces for a tab
vim.o.softtabstop = 4 -- Number of spaces that a tab counts for while performing editing operations
vim.o.expandtab = true -- convert tabs to spaces
vim.o.bri = true -- break indent
vim.o.showtabline = 1
vim.o.hls = false
vim.o.whichwrap = "b,s,<,>,[,],h,l"
